/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/delegates/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active delegates
         * @description Returns delegates who meet the voting activity threshold, sorted by voting power descending.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active delegates list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            count: number;
                            delegates: {
                                /** @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 */
                                address: string;
                                /** @example null */
                                ensName: string | null;
                                /** @example null */
                                avatarUrl: string | null;
                                /** @example 1000000000000000000000 */
                                votingPower: string;
                                /** @example 8 */
                                votesInLast10: number;
                                /**
                                 * @description Per-proposal voting record for the last 10 finalized proposals (most recent first)
                                 * @example [
                                 *       true,
                                 *       true,
                                 *       true,
                                 *       false,
                                 *       true,
                                 *       true,
                                 *       true,
                                 *       true,
                                 *       false,
                                 *       true
                                 *     ]
                                 */
                                last10ProposalsVoted: boolean[];
                                /** @example 42 */
                                delegatorCount: number;
                                /**
                                 * @description ISO 8601 timestamp of the delegate's earliest vote
                                 * @example 2024-01-15T00:00:00.000Z
                                 */
                                activeSince: string | null;
                            }[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eligibility/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check delegation eligibility
         * @description Checks whether an address is eligible for incentives by verifying it delegates (directly, via multi-delegate, or via Hedgey vesting) to an active delegate.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eligibility result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 */
                            address: string;
                            ensName: string | null;
                            isActiveDelegate: boolean;
                            isDelegatorToActiveDelegate: boolean;
                            eligible: boolean;
                            /** @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 */
                            delegatedTo: string | null;
                            delegatedToEnsName: string | null;
                            /**
                             * @example direct
                             * @enum {string|null}
                             */
                            source: "direct" | "multidelegate" | "hedgey_vesting" | null;
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/estimate/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate rewards for an address
         * @description Estimates delegate and delegator rewards for the current month based on current VP, delegation state, and tier.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reward estimate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 500000000000000000000 */
                            delegateReward: string;
                            /** @example 150000000000000000000 */
                            delegatorReward: string;
                            /** @example 650000000000000000000 */
                            combinedReward: string;
                            aboveThreshold: boolean;
                            /** @example 1 */
                            currentTier: number;
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apy/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate APY and rewards for an address
         * @description Returns role, delegation info, estimated monthly reward, APY, and lottery qualification for the given address.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description APY estimate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address: string;
                            ensName: string | null;
                            avatarUrl: string | null;
                            /** @enum {string} */
                            role: "delegate" | "delegator" | "ineligible";
                            delegatedTo: string | null;
                            delegatedToEnsName: string | null;
                            delegatedToAvatarUrl: string | null;
                            poolSizeEns: string;
                            estimatedMonthlyRewardEns: string;
                            estimatedApyPct: string;
                            userShareWei: string;
                            totalShareWei: string;
                            currentBalanceEns: string;
                            qualifiesForLottery: boolean;
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rounds/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current incentive round
         * @description Returns the current round info: dates, progress, pool size, and active tier index.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current round info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Sequential round number (months since program start)
                             * @example 3
                             */
                            roundNumber: number;
                            /**
                             * @description ISO 8601 start of the round
                             * @example 2026-04-01T00:00:00.000Z
                             */
                            startDate: string;
                            /**
                             * @description ISO 8601 end of the round
                             * @example 2026-04-30T23:59:59.999Z
                             */
                            endDate: string;
                            /**
                             * @description Percentage of round elapsed (0-100)
                             * @example 53
                             */
                            percentComplete: number;
                            /** @example 14 */
                            daysRemaining: number;
                            /**
                             * @description Current tier pool size in ENS
                             * @example 5000.000000000000000000
                             */
                            poolSizeEns: string;
                            /** @example 1 */
                            tierIndex: number;
                            /**
                             * @description Month-over-month active VP growth percentage
                             * @example 9.09
                             */
                            vpGrowthPct: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiers/progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tier progression and current VP growth
         * @description Returns all tier definitions with current unlock state, VP thresholds, estimated APY, and overall VP growth.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tier progression data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Current active VP (wei)
                             * @example 107230000000000000000000
                             */
                            currentAVP: string;
                            /**
                             * @description Active VP at month start (wei)
                             * @example 100000000000000000000000
                             */
                            previousAVP: string;
                            /** @example 723 */
                            currentGrowthBps: string;
                            /** @example 7.23 */
                            currentGrowthPct: string;
                            /** @example 0 */
                            currentTierIndex: number;
                            /** @example 25 */
                            activeDelegateCount: number;
                            /**
                             * @description Highest estimated delegator APY across all tiers
                             * @example 54.00
                             */
                            maxDelegatorApyPct: string;
                            tiers: {
                                /** @example 0 */
                                index: number;
                                /** @example 0 */
                                momGrowthMinPct: string;
                                /** @example 10 */
                                momGrowthMaxPct: string;
                                /** @example 5000.000000000000000000 */
                                poolSizeEns: string;
                                /** @example 50.000000000000000000 */
                                delegateCapEns: string;
                                /** @example 250.000000000000000000 */
                                delegatorCapEns: string;
                                isCurrent: boolean;
                                isUnlocked: boolean;
                                /**
                                 * @description Wei needed above current VP to reach this tier
                                 * @example 0
                                 */
                                additionalVPNeeded: string;
                                /**
                                 * @description VP threshold to enter this tier (wei)
                                 * @example 110000000000000000000000
                                 */
                                requiredAVP: string;
                                /**
                                 * @description Estimated delegator APY at this tier
                                 * @example 12.50
                                 */
                                estimatedApyPct: string;
                            }[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List distribution months
         * @description Returns an array of YYYY-MM month strings for which distributions have been computed, most recent first.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Month list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributions/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get distribution for a month
         * @description Returns the curated distribution result for the requested month.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    month: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Distribution result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Invalid month format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Distribution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributions/{month}/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download distribution CSV
         * @description Returns the distribution for the requested month as a downloadable CSV file.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    month: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                /** @description Invalid month format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Distribution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System statistics
         * @description Returns active delegate count, total indexed proposals, and available distribution months.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 25 */
                            activeDelegateCount: number;
                            /** @example 142 */
                            proposalCount: number;
                            /**
                             * @example [
                             *       "2026-03",
                             *       "2026-02"
                             *     ]
                             */
                            cachedDistributions: string[];
                            /**
                             * @description Total ENS held by active delegates (sum of latest VP snapshots), formatted as ENS string
                             * @example 1250000.000000000000000000
                             */
                            totalDelegatedEns: string;
                            /**
                             * @description Count of unique addresses earning rewards (active delegates plus unique direct delegators to active delegates)
                             * @example 412
                             */
                            holdersEarning: number;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
