/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/voters/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active voters
         * @description Returns voters who meet the voting activity threshold, sorted by voting power descending.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active voters list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            count: number;
                            voters: {
                                /** @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 */
                                address: string;
                                /** @example null */
                                ensName: string | null;
                                /** @example null */
                                avatarUrl: string | null;
                                /** @example 1000000000000000000000 */
                                votingPower: string;
                                /** @example 8 */
                                votesInLast10: number;
                                /**
                                 * @description Per-proposal voting record for the last 10 finalized proposals (most recent first)
                                 * @example [
                                 *       true,
                                 *       true,
                                 *       true,
                                 *       false,
                                 *       true,
                                 *       true,
                                 *       true,
                                 *       true,
                                 *       false,
                                 *       true
                                 *     ]
                                 */
                                last10ProposalsVoted: boolean[];
                                /** @description Detailed per-proposal record (same order as last10ProposalsVoted) */
                                last10Proposals: {
                                    /** @example 39893466662181856279242827854933926689925858494049650894234231038376231891860 */
                                    proposalId: string;
                                    /** @example EP 6.6 — [Executable] Working Group budgets, Term 6 */
                                    title: string;
                                    /**
                                     * @description Proposal status (executed, succeeded, queued, defeated, expired)
                                     * @example executed
                                     */
                                    status: string;
                                    /**
                                     * @description Voter's vote: 0=Against, 1=For, 2=Abstain, null=did not vote
                                     * @example 1
                                     */
                                    voterSupport: number | null;
                                }[];
                                /** @example 42 */
                                tokenHolderCount: number;
                                /**
                                 * @description ISO 8601 timestamp of the voter's earliest vote
                                 * @example 2024-01-15T00:00:00.000Z
                                 */
                                activeSince: string | null;
                            }[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eligibility/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check delegation eligibility
         * @description Checks whether an address is eligible for incentives by verifying it delegates (directly, via multi-delegate, or via Hedgey vesting) to an active voter.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eligibility result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 */
                            address: string;
                            ensName: string | null;
                            isActiveVoter: boolean;
                            isTokenHolderOfActiveVoter: boolean;
                            eligible: boolean;
                            /** @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 */
                            delegatedTo: string | null;
                            delegatedToEnsName: string | null;
                            /**
                             * @example direct
                             * @enum {string|null}
                             */
                            source: "direct" | "multidelegate" | "hedgey_vesting" | null;
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/estimate/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate rewards for an address
         * @description Estimates voter and token-holder rewards for the current month based on current VP, delegation state, and tier.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reward estimate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 500000000000000000000 */
                            voterReward: string;
                            /** @example 150000000000000000000 */
                            tokenHolderReward: string;
                            /** @example 650000000000000000000 */
                            combinedReward: string;
                            aboveThreshold: boolean;
                            /** @example 1 */
                            currentTier: number;
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apr/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimate APR and rewards for an address
         * @description Returns role, delegation info, estimated monthly reward, APR, and lottery qualification for the given address.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description APR estimate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            address: string;
                            ensName: string | null;
                            avatarUrl: string | null;
                            /** @enum {string} */
                            role: "voter" | "token_holder" | "ineligible";
                            delegatedTo: string | null;
                            delegatedToEnsName: string | null;
                            delegatedToAvatarUrl: string | null;
                            poolSizeEns: string;
                            estimatedMonthlyRewardEns: string;
                            estimatedAprPct: string;
                            userShareWei: string;
                            totalShareWei: string;
                            currentBalanceEns: string;
                            qualifiesForLottery: boolean;
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rounds/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current incentive round
         * @description Returns current round dates, progress, pool size, and active tier index. Dates are UTC.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current round info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Sequential round number from ROUND_MONTHS
                             * @example 3
                             */
                            roundNumber: number;
                            /**
                             * @description ISO 8601 UTC start of the round
                             * @example 2026-05-01T00:00:00.000Z
                             */
                            startDate: string;
                            /**
                             * @description ISO 8601 UTC end of the round
                             * @example 2026-05-31T23:59:59.999Z
                             */
                            endDate: string;
                            /**
                             * @description Percentage of round elapsed (0-100)
                             * @example 10
                             */
                            percentComplete: number;
                            /** @example 28 */
                            daysRemaining: number;
                            /**
                             * @description Current round tier pool size in ENS
                             * @example 5000.000000000000000000
                             */
                            poolSizeEns: string;
                            /** @example 0 */
                            tierIndex: number;
                            /**
                             * @description Current month active VP growth percentage
                             * @example 0.00
                             */
                            vpGrowthPct: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List configured rounds with reward summaries
         * @description Returns all configured ROUND_MONTHS rounds with UTC dates, global pool/distribution metadata when available, and truthful missing-data states.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Round summaries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            currentRoundNumber: number | null;
                            rounds: {
                                roundNumber: number;
                                month: string;
                                startDate: string;
                                endDate: string;
                                /** @enum {string} */
                                status: "live" | "ended" | "pending" | "paid";
                                /** @enum {string} */
                                distributionDataStatus: "available" | "in_progress" | "missing" | "not_started";
                                isCurrent: boolean;
                                percentComplete: number | null;
                                daysRemaining: number | null;
                                tierIndex: number | null;
                                tierLabel: string | null;
                                vpGrowthPct: string | null;
                                poolSize: string | null;
                                poolSizeEns: string | null;
                                totalDistributed: string | null;
                                totalDistributedEns: string | null;
                                activeVoterCount: number | null;
                                /**
                                 * @description Computed round count of direct payout rows with a positive token-holder reward. Excludes sub-1 ENS lottery entries and lottery-only winners.
                                 * @example 312
                                 */
                                eligibleTokenHolderCount: number | null;
                                /**
                                 * @description Number of deterministic lottery buckets formed from sub-1 ENS entries.
                                 * @example 53
                                 */
                                lotteryBucketCount: number | null;
                                /**
                                 * @description Number of sub-threshold reward entries participating in the lottery.
                                 * @example 2597
                                 */
                                lotteryEntryCount: number | null;
                                /**
                                 * @description Unique address count across lottery entries.
                                 * @example 2597
                                 */
                                lotteryParticipantCount: number | null;
                                /**
                                 * @description Unique lottery winner count.
                                 * @example 53
                                 */
                                lotteryWinnerCount: number | null;
                                lotteryPrize: string | null;
                                lotteryPrizeEns: string | null;
                                computedAt: string | null;
                            }[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rounds/{roundNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get round details
         * @description Returns one round's global reward summary, optional address-specific reward, and top delegate/token-holder rewards when distribution data exists.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional Ethereum address for wallet-specific round earnings */
                    address?: string;
                    /** @description Reward ranking rows to return on round detail. Defaults to 10. Use all to return every reward row. */
                    rewardLimit?: string;
                };
                header?: never;
                path: {
                    roundNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Round detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            roundNumber: number;
                            month: string;
                            startDate: string;
                            endDate: string;
                            /** @enum {string} */
                            status: "live" | "ended" | "pending" | "paid";
                            /** @enum {string} */
                            distributionDataStatus: "available" | "in_progress" | "missing" | "not_started";
                            isCurrent: boolean;
                            percentComplete: number | null;
                            daysRemaining: number | null;
                            tierIndex: number | null;
                            tierLabel: string | null;
                            vpGrowthPct: string | null;
                            poolSize: string | null;
                            poolSizeEns: string | null;
                            totalDistributed: string | null;
                            totalDistributedEns: string | null;
                            activeVoterCount: number | null;
                            /**
                             * @description Computed round count of direct payout rows with a positive token-holder reward. Excludes sub-1 ENS lottery entries and lottery-only winners.
                             * @example 312
                             */
                            eligibleTokenHolderCount: number | null;
                            /**
                             * @description Number of deterministic lottery buckets formed from sub-1 ENS entries.
                             * @example 53
                             */
                            lotteryBucketCount: number | null;
                            /**
                             * @description Number of sub-threshold reward entries participating in the lottery.
                             * @example 2597
                             */
                            lotteryEntryCount: number | null;
                            /**
                             * @description Unique address count across lottery entries.
                             * @example 2597
                             */
                            lotteryParticipantCount: number | null;
                            /**
                             * @description Unique lottery winner count.
                             * @example 53
                             */
                            lotteryWinnerCount: number | null;
                            lotteryPrize: string | null;
                            lotteryPrizeEns: string | null;
                            computedAt: string | null;
                            addressReward: {
                                address: string;
                                /** @enum {string} */
                                rewardStatus: "paid" | "no_reward" | "not_eligible" | "pending" | "unavailable";
                                voterReward: string;
                                voterRewardEns: string;
                                tokenHolderReward: string;
                                tokenHolderRewardEns: string;
                                lotteryReward: string;
                                lotteryRewardEns: string;
                                totalReward: string;
                                totalRewardEns: string;
                                /** @description Per-wallet allocation provenance (averages, pool share, pre-cap allocation, cap redistribution). Null for rounds whose persisted result predates provenance tracking (never recomputed) and for rewardStatus pending/unavailable/not_eligible. Lottery winnings carry no provenance — seed and odds live in the lottery payload. */
                                provenance: {
                                    /** @description Delegate (voter) reward provenance. Null when the wallet earned no voter reward. */
                                    voter: {
                                        /**
                                         * @description Time-weighted average voting power (TWAP) over the round month, in Wei.
                                         * @example 1234560000000000000000
                                         */
                                        avgVotingPower: string;
                                        /**
                                         * @description avgVotingPower formatted in ENS (18 decimals).
                                         * @example 1234.560000000000000000
                                         */
                                        avgVotingPowerEns: string;
                                        /**
                                         * @description Share of the voter pool, percent string with 2 decimals (style: vpGrowthPct).
                                         * @example 3.21
                                         */
                                        poolSharePct: string;
                                        /**
                                         * @description Pre-cap pro-rata allocation, in Wei.
                                         * @example 15100000000000000000
                                         */
                                        rawReward: string;
                                        /**
                                         * @description rawReward formatted in ENS (18 decimals).
                                         * @example 15.100000000000000000
                                         */
                                        rawRewardEns: string;
                                        /**
                                         * @description Post-cap allocation, in Wei. Equals voterReward.
                                         * @example 12400000000000000000
                                         */
                                        finalReward: string;
                                        /**
                                         * @description finalReward formatted in ENS (18 decimals).
                                         * @example 12.400000000000000000
                                         */
                                        finalRewardEns: string;
                                        /**
                                         * @description Resolved per-voter cap for the round (1% of the pool), in Wei.
                                         * @example 250000000000000000000
                                         */
                                        cap: string;
                                        /**
                                         * @description cap formatted in ENS (18 decimals).
                                         * @example 250.000000000000000000
                                         */
                                        capEns: string;
                                        /**
                                         * @description How cap redistribution affected the allocation: not_affected (final equals raw pro-rata), received_redistribution (received excess from capped wallets), reached_cap (clamped at the per-wallet cap).
                                         * @example not_affected
                                         * @enum {string}
                                         */
                                        capStatus: "not_affected" | "received_redistribution" | "reached_cap";
                                        /**
                                         * @description Excess received from capped wallets, in Wei. "0" unless capStatus is received_redistribution.
                                         * @example 0
                                         */
                                        redistributionReceived: string;
                                        /**
                                         * @description redistributionReceived formatted in ENS (18 decimals).
                                         * @example 0.000000000000000000
                                         */
                                        redistributionReceivedEns: string;
                                    } | null;
                                    /** @description Token-holder reward provenance. Null when the wallet earned no token-holder reward. */
                                    tokenHolder: {
                                        /**
                                         * @description Time-weighted ENS balance (TWB) over the trailing 180-day window, in Wei.
                                         * @example 1234560000000000000000
                                         */
                                        avgBalance: string;
                                        /**
                                         * @description avgBalance formatted in ENS (18 decimals).
                                         * @example 1234.560000000000000000
                                         */
                                        avgBalanceEns: string;
                                        /**
                                         * @description Share of the token-holder pool, percent string with 2 decimals (style: vpGrowthPct).
                                         * @example 3.21
                                         */
                                        poolSharePct: string;
                                        /**
                                         * @description Pre-cap pro-rata allocation, in Wei.
                                         * @example 15100000000000000000
                                         */
                                        rawReward: string;
                                        /**
                                         * @description rawReward formatted in ENS (18 decimals).
                                         * @example 15.100000000000000000
                                         */
                                        rawRewardEns: string;
                                        /**
                                         * @description Post-cap allocation, in Wei. Equals tokenHolderReward.
                                         * @example 12400000000000000000
                                         */
                                        finalReward: string;
                                        /**
                                         * @description finalReward formatted in ENS (18 decimals).
                                         * @example 12.400000000000000000
                                         */
                                        finalRewardEns: string;
                                        /**
                                         * @description Resolved per-token-holder cap for the round (5% of the pool), in Wei.
                                         * @example 250000000000000000000
                                         */
                                        cap: string;
                                        /**
                                         * @description cap formatted in ENS (18 decimals).
                                         * @example 250.000000000000000000
                                         */
                                        capEns: string;
                                        /**
                                         * @description How cap redistribution affected the allocation: not_affected (final equals raw pro-rata), received_redistribution (received excess from capped wallets), reached_cap (clamped at the per-wallet cap).
                                         * @example not_affected
                                         * @enum {string}
                                         */
                                        capStatus: "not_affected" | "received_redistribution" | "reached_cap";
                                        /**
                                         * @description Excess received from capped wallets, in Wei. "0" unless capStatus is received_redistribution.
                                         * @example 0
                                         */
                                        redistributionReceived: string;
                                        /**
                                         * @description redistributionReceived formatted in ENS (18 decimals).
                                         * @example 0.000000000000000000
                                         */
                                        redistributionReceivedEns: string;
                                        /**
                                         * @description Deduplicated holding kinds backing the consolidated balance. Null when the round's stored data does not track sources.
                                         * @example [
                                         *       "direct",
                                         *       "multidelegate",
                                         *       "hedgey"
                                         *     ]
                                         */
                                        sources: ("direct" | "multidelegate" | "hedgey")[] | null;
                                    } | null;
                                } | null;
                            } | null;
                            topVoterRewards: {
                                rank: number;
                                address: string;
                                ensName: string | null;
                                /** @enum {string} */
                                role: "voter" | "token_holder";
                                reward: string;
                                rewardEns: string;
                                /** @enum {string} */
                                source: "direct" | "lottery" | "combined";
                                votingPower: string | null;
                                /**
                                 * @description Time-weighted ENS balance backing the token-holder reward (Wei). Null for voter rows and for historic rounds computed before this field was persisted.
                                 * @example 1500000000000000000000
                                 */
                                tokenHolderBalance: string | null;
                                delegationCount: number | null;
                            }[];
                            topTokenHolderRewards: {
                                rank: number;
                                address: string;
                                ensName: string | null;
                                /** @enum {string} */
                                role: "voter" | "token_holder";
                                reward: string;
                                rewardEns: string;
                                /** @enum {string} */
                                source: "direct" | "lottery" | "combined";
                                votingPower: string | null;
                                /**
                                 * @description Time-weighted ENS balance backing the token-holder reward (Wei). Null for voter rows and for historic rounds computed before this field was persisted.
                                 * @example 1500000000000000000000
                                 */
                                tokenHolderBalance: string | null;
                                delegationCount: number | null;
                            }[];
                            lottery: {
                                seed: {
                                    /** @enum {string} */
                                    source: "ethereum_prev_randao";
                                    label: string;
                                    value: string;
                                    blockNumber: string;
                                    algorithm: string;
                                };
                                bucketTarget: string;
                                bucketTargetEns: string;
                                totalPrize: string;
                                totalPrizeEns: string;
                                bucketCount: number;
                                entryCount: number;
                                participantCount: number;
                                winnerCount: number;
                                buckets: {
                                    bucketIndex: number;
                                    prize: string;
                                    prizeEns: string;
                                    winner: string;
                                    winnerEnsName: string | null;
                                    winnerProbability: string | null;
                                    entryCount: number;
                                    entries: {
                                        bucketIndex: number;
                                        entryIndex: number;
                                        address: string;
                                        ensName: string | null;
                                        amount: string;
                                        amountEns: string;
                                        /**
                                         * @description Entry win probability inside the bucket, formatted as a 0-1 decimal string.
                                         * @example 0.1250
                                         */
                                        probability: string;
                                    }[];
                                }[];
                            } | null;
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Unknown round */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rounds/{roundNumber}/distributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get round distribution rankings
         * @description Returns top delegate and token-holder rewards for one round when stored distribution data exists.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional Ethereum address for wallet-specific round earnings */
                    address?: string;
                    /** @description Reward ranking rows to return on round detail. Defaults to 10. Use all to return every reward row. */
                    rewardLimit?: string;
                };
                header?: never;
                path: {
                    roundNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Round distribution detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            roundNumber: number;
                            month: string;
                            startDate: string;
                            endDate: string;
                            /** @enum {string} */
                            status: "live" | "ended" | "pending" | "paid";
                            /** @enum {string} */
                            distributionDataStatus: "available" | "in_progress" | "missing" | "not_started";
                            isCurrent: boolean;
                            percentComplete: number | null;
                            daysRemaining: number | null;
                            tierIndex: number | null;
                            tierLabel: string | null;
                            vpGrowthPct: string | null;
                            poolSize: string | null;
                            poolSizeEns: string | null;
                            totalDistributed: string | null;
                            totalDistributedEns: string | null;
                            activeVoterCount: number | null;
                            /**
                             * @description Computed round count of direct payout rows with a positive token-holder reward. Excludes sub-1 ENS lottery entries and lottery-only winners.
                             * @example 312
                             */
                            eligibleTokenHolderCount: number | null;
                            /**
                             * @description Number of deterministic lottery buckets formed from sub-1 ENS entries.
                             * @example 53
                             */
                            lotteryBucketCount: number | null;
                            /**
                             * @description Number of sub-threshold reward entries participating in the lottery.
                             * @example 2597
                             */
                            lotteryEntryCount: number | null;
                            /**
                             * @description Unique address count across lottery entries.
                             * @example 2597
                             */
                            lotteryParticipantCount: number | null;
                            /**
                             * @description Unique lottery winner count.
                             * @example 53
                             */
                            lotteryWinnerCount: number | null;
                            lotteryPrize: string | null;
                            lotteryPrizeEns: string | null;
                            computedAt: string | null;
                            addressReward: {
                                address: string;
                                /** @enum {string} */
                                rewardStatus: "paid" | "no_reward" | "not_eligible" | "pending" | "unavailable";
                                voterReward: string;
                                voterRewardEns: string;
                                tokenHolderReward: string;
                                tokenHolderRewardEns: string;
                                lotteryReward: string;
                                lotteryRewardEns: string;
                                totalReward: string;
                                totalRewardEns: string;
                                /** @description Per-wallet allocation provenance (averages, pool share, pre-cap allocation, cap redistribution). Null for rounds whose persisted result predates provenance tracking (never recomputed) and for rewardStatus pending/unavailable/not_eligible. Lottery winnings carry no provenance — seed and odds live in the lottery payload. */
                                provenance: {
                                    /** @description Delegate (voter) reward provenance. Null when the wallet earned no voter reward. */
                                    voter: {
                                        /**
                                         * @description Time-weighted average voting power (TWAP) over the round month, in Wei.
                                         * @example 1234560000000000000000
                                         */
                                        avgVotingPower: string;
                                        /**
                                         * @description avgVotingPower formatted in ENS (18 decimals).
                                         * @example 1234.560000000000000000
                                         */
                                        avgVotingPowerEns: string;
                                        /**
                                         * @description Share of the voter pool, percent string with 2 decimals (style: vpGrowthPct).
                                         * @example 3.21
                                         */
                                        poolSharePct: string;
                                        /**
                                         * @description Pre-cap pro-rata allocation, in Wei.
                                         * @example 15100000000000000000
                                         */
                                        rawReward: string;
                                        /**
                                         * @description rawReward formatted in ENS (18 decimals).
                                         * @example 15.100000000000000000
                                         */
                                        rawRewardEns: string;
                                        /**
                                         * @description Post-cap allocation, in Wei. Equals voterReward.
                                         * @example 12400000000000000000
                                         */
                                        finalReward: string;
                                        /**
                                         * @description finalReward formatted in ENS (18 decimals).
                                         * @example 12.400000000000000000
                                         */
                                        finalRewardEns: string;
                                        /**
                                         * @description Resolved per-voter cap for the round (1% of the pool), in Wei.
                                         * @example 250000000000000000000
                                         */
                                        cap: string;
                                        /**
                                         * @description cap formatted in ENS (18 decimals).
                                         * @example 250.000000000000000000
                                         */
                                        capEns: string;
                                        /**
                                         * @description How cap redistribution affected the allocation: not_affected (final equals raw pro-rata), received_redistribution (received excess from capped wallets), reached_cap (clamped at the per-wallet cap).
                                         * @example not_affected
                                         * @enum {string}
                                         */
                                        capStatus: "not_affected" | "received_redistribution" | "reached_cap";
                                        /**
                                         * @description Excess received from capped wallets, in Wei. "0" unless capStatus is received_redistribution.
                                         * @example 0
                                         */
                                        redistributionReceived: string;
                                        /**
                                         * @description redistributionReceived formatted in ENS (18 decimals).
                                         * @example 0.000000000000000000
                                         */
                                        redistributionReceivedEns: string;
                                    } | null;
                                    /** @description Token-holder reward provenance. Null when the wallet earned no token-holder reward. */
                                    tokenHolder: {
                                        /**
                                         * @description Time-weighted ENS balance (TWB) over the trailing 180-day window, in Wei.
                                         * @example 1234560000000000000000
                                         */
                                        avgBalance: string;
                                        /**
                                         * @description avgBalance formatted in ENS (18 decimals).
                                         * @example 1234.560000000000000000
                                         */
                                        avgBalanceEns: string;
                                        /**
                                         * @description Share of the token-holder pool, percent string with 2 decimals (style: vpGrowthPct).
                                         * @example 3.21
                                         */
                                        poolSharePct: string;
                                        /**
                                         * @description Pre-cap pro-rata allocation, in Wei.
                                         * @example 15100000000000000000
                                         */
                                        rawReward: string;
                                        /**
                                         * @description rawReward formatted in ENS (18 decimals).
                                         * @example 15.100000000000000000
                                         */
                                        rawRewardEns: string;
                                        /**
                                         * @description Post-cap allocation, in Wei. Equals tokenHolderReward.
                                         * @example 12400000000000000000
                                         */
                                        finalReward: string;
                                        /**
                                         * @description finalReward formatted in ENS (18 decimals).
                                         * @example 12.400000000000000000
                                         */
                                        finalRewardEns: string;
                                        /**
                                         * @description Resolved per-token-holder cap for the round (5% of the pool), in Wei.
                                         * @example 250000000000000000000
                                         */
                                        cap: string;
                                        /**
                                         * @description cap formatted in ENS (18 decimals).
                                         * @example 250.000000000000000000
                                         */
                                        capEns: string;
                                        /**
                                         * @description How cap redistribution affected the allocation: not_affected (final equals raw pro-rata), received_redistribution (received excess from capped wallets), reached_cap (clamped at the per-wallet cap).
                                         * @example not_affected
                                         * @enum {string}
                                         */
                                        capStatus: "not_affected" | "received_redistribution" | "reached_cap";
                                        /**
                                         * @description Excess received from capped wallets, in Wei. "0" unless capStatus is received_redistribution.
                                         * @example 0
                                         */
                                        redistributionReceived: string;
                                        /**
                                         * @description redistributionReceived formatted in ENS (18 decimals).
                                         * @example 0.000000000000000000
                                         */
                                        redistributionReceivedEns: string;
                                        /**
                                         * @description Deduplicated holding kinds backing the consolidated balance. Null when the round's stored data does not track sources.
                                         * @example [
                                         *       "direct",
                                         *       "multidelegate",
                                         *       "hedgey"
                                         *     ]
                                         */
                                        sources: ("direct" | "multidelegate" | "hedgey")[] | null;
                                    } | null;
                                } | null;
                            } | null;
                            topVoterRewards: {
                                rank: number;
                                address: string;
                                ensName: string | null;
                                /** @enum {string} */
                                role: "voter" | "token_holder";
                                reward: string;
                                rewardEns: string;
                                /** @enum {string} */
                                source: "direct" | "lottery" | "combined";
                                votingPower: string | null;
                                /**
                                 * @description Time-weighted ENS balance backing the token-holder reward (Wei). Null for voter rows and for historic rounds computed before this field was persisted.
                                 * @example 1500000000000000000000
                                 */
                                tokenHolderBalance: string | null;
                                delegationCount: number | null;
                            }[];
                            topTokenHolderRewards: {
                                rank: number;
                                address: string;
                                ensName: string | null;
                                /** @enum {string} */
                                role: "voter" | "token_holder";
                                reward: string;
                                rewardEns: string;
                                /** @enum {string} */
                                source: "direct" | "lottery" | "combined";
                                votingPower: string | null;
                                /**
                                 * @description Time-weighted ENS balance backing the token-holder reward (Wei). Null for voter rows and for historic rounds computed before this field was persisted.
                                 * @example 1500000000000000000000
                                 */
                                tokenHolderBalance: string | null;
                                delegationCount: number | null;
                            }[];
                            lottery: {
                                seed: {
                                    /** @enum {string} */
                                    source: "ethereum_prev_randao";
                                    label: string;
                                    value: string;
                                    blockNumber: string;
                                    algorithm: string;
                                };
                                bucketTarget: string;
                                bucketTargetEns: string;
                                totalPrize: string;
                                totalPrizeEns: string;
                                bucketCount: number;
                                entryCount: number;
                                participantCount: number;
                                winnerCount: number;
                                buckets: {
                                    bucketIndex: number;
                                    prize: string;
                                    prizeEns: string;
                                    winner: string;
                                    winnerEnsName: string | null;
                                    winnerProbability: string | null;
                                    entryCount: number;
                                    entries: {
                                        bucketIndex: number;
                                        entryIndex: number;
                                        address: string;
                                        ensName: string | null;
                                        amount: string;
                                        amountEns: string;
                                        /**
                                         * @description Entry win probability inside the bucket, formatted as a 0-1 decimal string.
                                         * @example 0.1250
                                         */
                                        probability: string;
                                    }[];
                                }[];
                            } | null;
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Unknown round */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiers/progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tier progression and current VP growth
         * @description Returns all tier definitions with current unlock state, VP thresholds, estimated APR, and overall VP growth.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tier progression data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Current total VP held by active voters (wei)
                             * @example 107230000000000000000000
                             */
                            currentTotalVP: string;
                            /**
                             * @description Total VP at month start (wei)
                             * @example 100000000000000000000000
                             */
                            previousTotalVP: string;
                            /** @example 723 */
                            currentGrowthBps: string;
                            /** @example 7.23 */
                            currentGrowthPct: string;
                            /** @example 0 */
                            currentTierIndex: number;
                            /** @example 25 */
                            activeVoterCount: number;
                            /**
                             * @description Highest estimated token-holder APR across all tiers
                             * @example 54.00
                             */
                            maxTokenHolderAprPct: string;
                            tiers: {
                                /** @example 0 */
                                index: number;
                                /** @example 0 */
                                momGrowthMinPct: string;
                                /** @example 10 */
                                momGrowthMaxPct: string;
                                /** @example 5000.000000000000000000 */
                                poolSizeEns: string;
                                /** @example 50.000000000000000000 */
                                voterCapEns: string;
                                /** @example 250.000000000000000000 */
                                tokenHolderCapEns: string;
                                isCurrent: boolean;
                                isUnlocked: boolean;
                                /**
                                 * @description Wei needed above current VP to reach this tier
                                 * @example 0
                                 */
                                additionalVPNeeded: string;
                                /**
                                 * @description VP threshold to enter this tier (wei)
                                 * @example 110000000000000000000000
                                 */
                                requiredTotalVP: string;
                                /**
                                 * @description Estimated token-holder APR at this tier (calibrated against round-start VP)
                                 * @example 12.50
                                 */
                                estimatedAprPct: string;
                            }[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List distribution months or address history
         * @description Without query parameters, returns an array of YYYY-MM month strings for computed distributions. With ?address=0x..., returns that address's per-round distribution history derived from stored results.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional Ethereum address for address-specific distribution history */
                    address?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Distribution month list or address distribution history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[] | {
                            address: string;
                            rounds: {
                                roundNumber: number;
                                month: string;
                                startDate: string;
                                endDate: string;
                                /** @enum {string} */
                                roundStatus: "live" | "ended" | "pending" | "paid";
                                /** @enum {string} */
                                distributionDataStatus: "available" | "in_progress" | "missing" | "not_started";
                                /** @enum {string} */
                                rewardStatus: "paid" | "no_reward" | "not_eligible" | "pending" | "unavailable";
                                voterReward: string;
                                voterRewardEns: string;
                                tokenHolderReward: string;
                                tokenHolderRewardEns: string;
                                lotteryReward: string;
                                lotteryRewardEns: string;
                                totalReward: string;
                                totalRewardEns: string;
                            }[];
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributions/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get distribution for a month
         * @description Returns the curated distribution result for the requested month.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    month: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Distribution result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Invalid month format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Distribution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributions/{month}/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download distribution CSV
         * @description Returns the distribution for the requested month as a downloadable CSV file.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    month: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                /** @description Invalid month format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Distribution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System statistics
         * @description Returns active voter count, total indexed proposals, and available distribution months.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 25 */
                            activeVoterCount: number;
                            /** @example 142 */
                            proposalCount: number;
                            /**
                             * @example [
                             *       "2026-03",
                             *       "2026-02"
                             *     ]
                             */
                            cachedDistributions: string[];
                            /**
                             * @description Total ENS held by active voters (sum of latest VP snapshots), formatted as ENS string
                             * @example 1250000.000000000000000000
                             */
                            totalDelegatedEns: string;
                            /**
                             * @description Current count of active voters plus unique direct token holders of active voters with a positive ENS balance. This is live delegation state, not finalized round payout recipients.
                             * @example 412
                             */
                            holdersEarning: number;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/selections/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an address's word selection (public)
         * @description Returns the stored word selection for any address. Public — selections are not private. 404 when the address has no selection.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The address's selection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 */
                            address: string;
                            /**
                             * @example [
                             *       "security",
                             *       "decentralization",
                             *       "public_goods_funding",
                             *       "transparency",
                             *       "open_source"
                             *     ]
                             */
                            words: string[];
                            /**
                             * @description Last-write Unix time in ms
                             * @example 1781619462005
                             */
                            updatedAt: number;
                        };
                    };
                };
                /** @description Invalid address */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description No selection for this address */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        /**
         * Upsert an address's word selection
         * @description Stores (or replaces) the word selection for the path `address`. The body must include a `personal_sign` signature over `buildSelectionMessage(address, words)`; the recovered signer must equal the path `address`. Idempotent upsert keyed by address.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Exactly 5 word ids from the pool (unordered set) */
                        words: string[];
                        /**
                         * @description personal_sign signature over buildSelectionMessage(address, words)
                         * @example 0x...
                         */
                        signature: string;
                    };
                };
            };
            responses: {
                /** @description Stored selection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 */
                            address: string;
                            /**
                             * @example [
                             *       "security",
                             *       "decentralization",
                             *       "public_goods_funding",
                             *       "transparency",
                             *       "open_source"
                             *     ]
                             */
                            words: string[];
                            /**
                             * @description Last-write Unix time in ms
                             * @example 1781619462005
                             */
                            updatedAt: number;
                        };
                    };
                };
                /** @description Invalid address or selection */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Signature missing, malformed, or not from the path address */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
